### ISSUE TITLE
Error when attempting to import C18723582

### ISSUE THREAD

**Issue by DaleMitchell** [uPesy/easyeda2kicad.py#116]
python -m easyeda2kicad --full --lcsc_id C18723582
-- easyeda2kicad.py v0.6.5 --
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\dale\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\easyeda2kicad\__main__.py", line 361, in <module>
    sys.exit(main(sys.argv[1:]))
             ^^^^^^^^^^^^^^^^^^
  File "C:\Users\dale\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\easyeda2kicad\__main__.py", line 273, in main
    exporter = ExporterSymbolKicad(
               ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dale\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\easyeda2kicad\kicad\export_kicad_symbol.py", line 362, in __init__
    convert_to_kicad(ee_symbol=self.input, kicad_version=kicad_version)
  File "C:\Users\dale\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\easyeda2kicad\kicad\export_kicad_symbol.py", line 313, in convert_to_kicad
    pins=convert_ee_pins(
         ^^^^^^^^^^^^^^^^
  File "C:\Users\dale\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\easyeda2kicad\kicad\export_kicad_symbol.py", line 53, in convert_ee_pins
    pin_length = abs(int(float(ee_pin.pin_path.path.split("h")[-1])))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: could not convert string to float: ' 10 NaN'

**Comment by uPesy** [comment]
Fix in #184
