### ISSUE TITLE
C2904734 is causing divide by 0 error

### ISSUE THREAD

**Issue by DanielMazurkiewicz** [uPesy/easyeda2kicad.py#125]
```
C2904734
-- easyeda2kicad.py v0.7.0 --
Traceback (most recent call last):
  File "/home/d/.local/bin/easyeda2kicad", line 33, in <module>
    sys.exit(load_entry_point('easyeda2kicad==0.7.0', 'console_scripts', 'easyeda2kicad')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/d/.local/lib/python3.11/site-packages/easyeda2kicad-0.7.0-py3.11.egg/easyeda2kicad/__main__.py", line 273, in main
    exporter = ExporterSymbolKicad(
               ^^^^^^^^^^^^^^^^^^^^
  File "/home/d/.local/lib/python3.11/site-packages/easyeda2kicad-0.7.0-py3.11.egg/easyeda2kicad/kicad/export_kicad_symbol.py", line 362, in __init__
    convert_to_kicad(ee_symbol=self.input, kicad_version=kicad_version)
  File "/home/d/.local/lib/python3.11/site-packages/easyeda2kicad-0.7.0-py3.11.egg/easyeda2kicad/kicad/export_kicad_symbol.py", line 326, in convert_to_kicad
    arcs=convert_ee_arcs(
         ^^^^^^^^^^^^^^^^
  File "/home/d/.local/lib/python3.11/site-packages/easyeda2kicad-0.7.0-py3.11.egg/easyeda2kicad/kicad/export_kicad_symbol.py", line 169, in convert_ee_arcs
    center_x, center_y, angle_end = compute_arc(
                                    ^^^^^^^^^^^^
  File "/home/d/.local/lib/python3.11/site-packages/easyeda2kicad-0.7.0-py3.11.egg/easyeda2kicad/kicad/export_kicad_footprint.py", line 76, in compute_arc
    cx1 = coef * ((radius_x * y1) / radius_y)
                  ~~~~~~~~~~~~~~~~^~~~~~~~~~
ZeroDivisionError: float division by zero
```

**Comment by sedevelops** [comment]
Similar issue here for part #  C5379893 :'

`-- easyeda2kicad.py v0.7.0 --
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/hal9001/Library/Python/3.9/lib/python/site-packages/easyeda2kicad/__main__.py", line 373, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/Users/hal9001/Library/Python/3.9/lib/python/site-packages/easyeda2kicad/__main__.py", line 273, in main
    exporter = ExporterSymbolKicad(
  File "/Users/hal9001/Library/Python/3.9/lib/python/site-packages/easyeda2kicad/kicad/export_kicad_symbol.py", line 362, in __init__
    convert_to_kicad(ee_symbol=self.input, kicad_version=kicad_version)
  File "/Users/hal9001/Library/Python/3.9/lib/python/site-packages/easyeda2kicad/kicad/export_kicad_symbol.py", line 326, in convert_to_kicad
    arcs=convert_ee_arcs(
  File "/Users/hal9001/Library/Python/3.9/lib/python/site-packages/easyeda2kicad/kicad/export_kicad_symbol.py", line 169, in convert_ee_arcs
    center_x, center_y, angle_end = compute_arc(
  File "/Users/hal9001/Library/Python/3.9/lib/python/site-packages/easyeda2kicad/kicad/export_kicad_footprint.py", line 76, in compute_arc
    cx1 = coef * ((radius_x * y1) / radius_y)
`

**Comment by uPesy** [comment]
Fix in #184
