### ISSUE TITLE
[Bug] 3d model import now broken

### ISSUE THREAD

**Issue by Kanken6174** [uPesy/easyeda2kicad.py#132]
Hi, it would seem that the 3d model importation has broken down overnight (worked yesterday), example:
```bash
➜  ~ easyeda2kicad --lcsc_id=C2040 --full --overwrite --debug
-- easyeda2kicad.py v0.7.0 --
[DEBUG] Starting new HTTPS connection (1): easyeda.com:443
[DEBUG] https://easyeda.com:443 "GET /api/products/C2040/components?version=6.4.19.5 HTTP/1.1" 200 None
[WARNING] Unknow symbol designator : T
[WARNING] Unknow symbol designator : T
[WARNING] This id is already in /home/kanken/Documents/Kicad/easyeda2kicad/easyeda2kicad.kicad_sym
[INFO] Created Kicad symbol for ID : C2040
       Symbol name : RP2040
       Library path : /home/kanken/Documents/Kicad/easyeda2kicad/easyeda2kicad.kicad_sym
[WARNING] The footprint for this id is already in /home/kanken/Documents/Kicad/easyeda2kicad/easyeda2kicad.pretty
[INFO] Created Kicad footprint for ID: C2040
       Footprint name: LQFN-56_L7.0-W7.0-P0.4-EP
       Footprint path: /home/kanken/Documents/Kicad/easyeda2kicad/easyeda2kicad.pretty/LQFN-56_L7.0-W7.0-P0.4-EP.kicad_mod
[DEBUG] Starting new HTTPS connection (1): easyeda.com:443
```
it hangs at that point and never finishes. If i cancel it with ctrl+c i get the follwing trace:
```bash
Traceback (most recent call last):
  File "/home/kanken/.local/bin//easyeda2kicad", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/kanken/.local/lib/python3.12/site-packages/easyeda2kicad/__main__.py", line 340, in main
    model_3d=Easyeda3dModelImporter(
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kanken/.local/lib/python3.12/site-packages/easyeda2kicad/easyeda/easyeda_importer.py", line 239, in __init__
    self.output = self.create_3d_model()
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kanken/.local/lib/python3.12/site-packages/easyeda2kicad/easyeda/easyeda_importer.py", line 251, in create_3d_model
    model_3d.raw_obj = EasyedaApi().get_raw_3d_model_obj(uuid=model_3d.uuid)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kanken/.local/lib/python3.12/site-packages/easyeda2kicad/easyeda/easyeda_api.py", line 44, in get_raw_3d_model_obj
    r = requests.get(
        ^^^^^^^^^^^^^
  File "/home/kanken/.local/lib/python3.12/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kanken/.local/lib/python3.12/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kanken/.local/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kanken/.local/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kanken/.local/lib/python3.12/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/urllib3/connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/urllib3/connectionpool.py", line 467, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3.12/site-packages/urllib3/connectionpool.py", line 462, in _make_request
    httplib_response = conn.getresponse()
                       ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/http/client.py", line 1428, in getresponse
    response.begin()
  File "/usr/lib/python3.12/http/client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/http/client.py", line 292, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/socket.py", line 707, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/ssl.py", line 1252, in recv_into
    return self.read(nbytes, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/ssl.py", line 1104, in read
    return self._sslobj.read(len, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by Kanken6174** [comment]
for the RP2040 for example the script tries to access `https://easyeda.com/analyzer/api/3dmodel/76b360a9d4c54384a4e47d7e5af156df` which no longer exists

**Comment by Kanken6174** [comment]
more specifically it seems that the 3dmodel endpoint no longer exists in the api, there is a `model` endpoint but not much else i can find

**Comment by Kanken6174** [comment]
the easyeda pro web client seems to grab its 3d models from this domain:
`https://modules.easyeda.com/3dmodel/76b360a9d4c54384a4e47d7e5af156df`

**Comment by Kanken6174** [comment]
changing this line:
ENDPOINT_3D_MODEL = "https://easyeda.com/analyzer/api/3dmodel/{uuid}"
to this:
ENDPOINT_3D_MODEL = "https://modules.easyeda.com/3dmodel/{uuid}"

fixes the issue. i'll open a pull request.
