### ISSUE TITLE
Using --full with no 3D model gets spurious error

### ISSUE THREAD

**Issue by LispEngineer** [uPesy/easyeda2kicad.py#152]
Hi there, when running a `--full` import on something that has no 3D model, the software crashes, even though it knows there is no 3D model from the given warning. Please see below.

Expected behavior: Warning that there is no 3D model, and saying it is skipped, and no error message.

```
python -m easyeda2kicad --full --lcsc_id=C22399679 --overwrite
-- easyeda2kicad.py v0.8.0 --
[WARNING] This id is already in ...easyeda2kicad/easyeda2kicad.kicad_sym
[INFO] Created Kicad symbol for ID : C22399679
       Symbol name : ISOM8711DFFR
       Library path : ...easyeda2kicad/easyeda2kicad.kicad_sym
[WARNING] The footprint for this id is already in ...easyeda2kicad/easyeda2kicad.pretty
[INFO] Created Kicad footprint for ID: C22399679
       Footprint name: SOIC-5_L4.8-W3.5-P1.27-LS7.0-BL
       Footprint path: ...easyeda2kicad/easyeda2kicad.pretty\SOIC-5_L4.8-W3.5-P1.27-LS7.0-BL.kicad_mod
[WARNING] No 3D model available for this component
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "...\Python\Python312\site-packages\easyeda2kicad\__main__.py", line 373, in <module>
    sys.exit(main(sys.argv[1:]))
             ^^^^^^^^^^^^^^^^^^
  File "...\Python\Python312\site-packages\easyeda2kicad\__main__.py", line 339, in main
    exporter = Exporter3dModelKicad(
               ^^^^^^^^^^^^^^^^^^^^^
  File "...\Python\Python312\site-packages\easyeda2kicad\kicad\export_kicad_3d_model.py", line 126, in __init__
    self.output_step = model_3d.step
                       ^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'step'
```

**Comment by uPesy** [comment]
Fix in #184
