### ISSUE TITLE
Crash when converting C157482

### ISSUE THREAD

**Issue by thenickdude** [uPesy/easyeda2kicad.py#154]
On version 0.8.0:

```
$ easyeda2kicad --full --lcsc_id=C157482
-- easyeda2kicad.py v0.8.0 --
[INFO] Created Kicad symbol for ID : C157482
       Symbol name : TS3DV642A0RUAR
       Library path : /Users/nick/Documents/Kicad/easyeda2kicad/easyeda2kicad.kicad_sym
Traceback (most recent call last):
  File "/usr/local/bin/easyeda2kicad", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/easyeda2kicad/__main__.py", line 314, in main
    ki_footprint = ExporterFootprintKicad(footprint=easyeda_footprint)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/easyeda2kicad/kicad/export_kicad_footprint.py", line 174, in __init__
    self.generate_kicad_footprint()
  File "/usr/local/lib/python3.11/site-packages/easyeda2kicad/kicad/export_kicad_footprint.py", line 305, in generate_kicad_footprint
    round(point_list[i + 2] - self.input.bbox.x, 2)
          ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for -: 'str' and 'float'
```

**Comment by uPesy** [comment]
Fix in #184
