### ISSUE TITLE
Crash when converting C5187472

### ISSUE THREAD

**Issue by larsmob** [uPesy/easyeda2kicad.py#155]
When running:
   easyeda2kicad --full --lcsc_id=C5187472
This is the output:
```
/Users/lem/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
-- easyeda2kicad.py v0.8.0 --
[INFO] Created Kicad symbol for ID : C5187472
       Symbol name : TYPE-C 16P QTWT
       Library path : /Users/lem/Documents/Kicad/easyeda2kicad/easyeda2kicad.kicad_sym
Traceback (most recent call last):
  File "/Users/lem/Library/Python/3.9/bin/easyeda2kicad", line 8, in <module>
    sys.exit(main())
  File "/Users/lem/Library/Python/3.9/lib/python/site-packages/easyeda2kicad/__main__.py", line 303, in main
    importer = EasyedaFootprintImporter(easyeda_cp_cad_data=cad_data)
  File "/Users/lem/Library/Python/3.9/lib/python/site-packages/easyeda2kicad/easyeda/easyeda_importer.py", line 150, in __init__
    ee_data_str=self.input["packageDetail"]["dataStr"],
KeyError: 'packageDetail'
```
I've converted quite a few parts with this script and this is the first time I've had an issue.

Lars.

**Comment by uPesy** [comment]
Fix in #184
