### ISSUE TITLE
Part not importing  C911202

### ISSUE THREAD

**Issue by SnowballsChance** [uPesy/easyeda2kicad.py#59]
thanks for a great tool - really appreciate the work you have put into it.

For part
C91120
Located at [https://lcsc.com/product-detail/Aluminum-Electrolytic-Capacitors-Leaded_TWBOR-CV100MG511BP_C911202.html](https://lcsc.com/product-detail/Aluminum-Electrolytic-Capacitors-Leaded_TWBOR-CV100MG511BP_C911202.html)

Tried to import with the following command:

`%  easyeda2kicad --full --overwrite --lcsc_id=C911202`

but got this output:

-- easyeda2kicad.py --
[-] {'success': False, 'code': 404, 'message': 'Component not found'}
Traceback (most recent call last):
  File "/opt/homebrew/bin/easyeda2kicad", line 8, in <module>
    sys.exit(main())
  File "/opt/homebrew/lib/python3.9/site-packages/easyeda2kicad/__main__.py", line 189, in main
    importer = easyeda_symbol_importer(easyeda_cp_cad_data=cad_data)
  File "/opt/homebrew/lib/python3.9/site-packages/easyeda2kicad/easyeda/easyeda_importer.py", line 15, in __init__
    ee_data_info=easyeda_cp_cad_data["dataStr"]["head"]["c_para"],
KeyError: 'dataStr'

I have since realised that the component is there but there is no EasyEDA symbol/model etc. 

I think the error message was a bit vague, on reading the error I thought it was a HTTP problem the error doesn't show what the  real problem is. Perhaps the tool could differentiate between problems: 

Non existent part,
No EasyEda model,
General HTTP problem

cheers
and thanks for such a helpful tool.

**Comment by SnowballsChance** [comment]
Just discovered I was using a pretty old version of easyeda2kicad. Updated and it is better.

Many thanks
