### ISSUE TITLE
Failed fetch of C1222408 pydantic " value is not a valid list (type=type_error.list)"

### ISSUE THREAD

**Issue by SnowballsChance** [uPesy/easyeda2kicad.py#60]
```
% easyeda2kicad --overwrite --full --lcsc_id=C1222408
-- easyeda2kicad.py v0.4.1 --
Traceback (most recent call last):
  File "/opt/homebrew/bin/easyeda2kicad", line 8, in <module>
    sys.exit(main())
  File "/opt/homebrew/lib/python3.9/site-packages/easyeda2kicad/__main__.py", line 257, in main
    importer = EasyedaSymbolImporter(easyeda_cp_cad_data=cad_data)
  File "/opt/homebrew/lib/python3.9/site-packages/easyeda2kicad/easyeda/easyeda_importer.py", line 111, in __init__
    self.output: EeSymbol = self.extract_easyeda_data(
  File "/opt/homebrew/lib/python3.9/site-packages/easyeda2kicad/easyeda/easyeda_importer.py", line 139, in extract_easyeda_data
    easyeda_handlers[designator](line, new_ee_symbol)
  File "/opt/homebrew/lib/python3.9/site-packages/easyeda2kicad/easyeda/easyeda_importer.py", line 91, in add_easyeda_arc
    EeSymbolArc(**dict(zip(EeSymbolArc.__fields__, arc_data.split("~")[1:])))
  File "pydantic/main.py", line 331, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for EeSymbolArc
helper_dots
  value is not a valid list (type=type_error.list)
```

Upon opening symbol editor in kicad this message popped up

```
Errors loading symbols:
Error loading symbol library easyeda2kicad.
Expecting 'input, output, bidirectional, tri_state, passive, unspecified, power_in, power_out, open_collector, open_emitter, free or no_connect' in '/Users/snowball/Documents/Kicad/easyeda2kicad/easyeda2kicad.kicad_sym', line 345, offset 12.
```

**Comment by uPesy** [comment]
Thanks for your report !
This issue is already fixed in the dev branch.
I have released a new version 0.5.4 on the master branch
You can update your version using `pip install -U easyeda2kicad`
